name: chat_app
description: "Un nouveau projet Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # Dernières versions compatibles avec Flutter et Dart
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5

  provider: ^6.1.2  
       # Version compatible avec Flutter et Dart 3
  image_picker: ^1.0.7  
  fluttertoast: ^8.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  firebase_auth_web: ^5.13.4
  cloud_firestore_web: ^4.3.4
  firebase_messaging_web: ^3.9.4
  firebase_storage_web: ^3.10.5

flutter:
  uses-material-design: true